spring.application.name=Tagalog01
server.port=8081
# データベース接続設定
spring.datasource.url=jdbc:postgresql://localhost:5432/dic_db3
spring.datasource.username=dic_user3
spring.datasource.password=pdic_user3
spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.configuration.map-underscore-to-camel-case=true

# logging.level.com.example.taskmate.repository=DEBUG

logging.level.com.example.tagalog01.repository=DEBUG